### ISSUE TITLE
Remove Memes?

### ISSUE THREAD

**Issue by Bartschinator** [Ocelotworks/OcelotBOT#1]
Hi,

OcelotBOT does not check for meme with duplicate names and doesn't allow to remove memes.
That leads to duplicated entrys when an URL changes but the new one can't be used under the correct name, you have to give it a new name.

**Comment by UnacceptableUse** [comment]
I've changed the way !meme works completely, I will be updating commands.md to reflect the change shortly, but you can now remove memes.
